apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: market
spec:
  selector:
    app: market
  ports:
  - name: http
    port: 80707070        # ← Должно быть 8070
    targetPort: 80707070  # ← Должно быть 8070
    protocol: TCP
  type: ClusterIP